apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mwo1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/mwo1
    server: 10.128.0.10
